'use client';

import { motion } from 'framer-motion';
import { GlassCard } from '@/components/ui/glass-card';

function Box({
  x,
  y,
  width,
  label,
  sublabel,
  accent = false,
}: {
  x: number;
  y: number;
  width: number;
  label: string;
  sublabel?: string;
  accent?: boolean;
}) {
  return (
    <g>
      <rect
        x={x}
        y={y}
        width={width}
        height={56}
        rx={12}
        fill={accent ? 'rgb(237 28 36 / 0.12)' : 'rgb(255 255 255 / 0.04)'}
        stroke={accent ? 'rgb(237 28 36 / 0.5)' : 'rgb(255 255 255 / 0.14)'}
      />
      <text
        x={x + width / 2}
        y={sublabel === undefined ? y + 33 : y + 26}
        textAnchor="middle"
        className="fill-white text-[13px] font-medium"
      >
        {label}
      </text>
      {sublabel !== undefined && (
        <text
          x={x + width / 2}
          y={y + 43}
          textAnchor="middle"
          className="fill-slate-500 text-[10px]"
        >
          {sublabel}
        </text>
      )}
    </g>
  );
}

function Arrow({ d }: { d: string }) {
  return (
    <path
      d={d}
      fill="none"
      stroke="rgb(148 163 184 / 0.45)"
      strokeWidth={1.5}
      markerEnd="url(#arrowhead)"
    />
  );
}

export function ArchitectureDiagram() {
  return (
    <section className="mx-auto max-w-5xl px-4 pb-28 sm:px-6">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-60px' }}
        transition={{ duration: 0.5 }}
      >
        <h2 className="mb-2 text-center text-2xl font-semibold text-white sm:text-3xl">
          How it works
        </h2>
        <p className="mb-10 text-center text-slate-400">
          One request, routed, generated locally when possible, verified before
          it returns.
        </p>
        <GlassCard className="overflow-x-auto p-4 sm:p-8">
          <svg
            viewBox="0 0 760 340"
            className="mx-auto min-w-[640px]"
            role="img"
            aria-label="OmniAgent architecture: a task flows through the router to a capability, is generated by the hybrid provider on local vLLM with Fireworks fallback, then verified before the response returns"
          >
            <defs>
              <marker
                id="arrowhead"
                markerWidth={8}
                markerHeight={8}
                refX={7}
                refY={4}
                orient="auto"
              >
                <path d="M0,0 L8,4 L0,8" fill="rgb(148 163 184 / 0.45)" />
              </marker>
            </defs>

            <Box
              x={20}
              y={142}
              width={120}
              label="JSON Task"
              sublabel="POST /agent/tasks"
            />
            <Arrow d="M140,170 L188,170" />

            <Box
              x={190}
              y={142}
              width={130}
              label="Task Router"
              sublabel="capability match"
            />
            <Arrow d="M320,170 L368,170" />

            <Box
              x={370}
              y={142}
              width={130}
              label="Capability"
              sublabel="qa · math · codegen …"
            />
            <Arrow d="M500,170 L548,170" />

            <Box
              x={550}
              y={142}
              width={140}
              label="Hybrid Provider"
              sublabel="local-first"
              accent
            />

            <Arrow d="M620,142 C620,100 620,88 620,86" />
            <Box
              x={550}
              y={30}
              width={140}
              label="Local vLLM"
              sublabel="primary"
            />

            <Arrow d="M620,198 C620,240 620,252 620,254" />
            <Box
              x={550}
              y={254}
              width={140}
              label="Fireworks AI"
              sublabel="confidence fallback"
            />

            <Arrow d="M550,170 C480,170 470,230 435,254" />
            <Box
              x={300}
              y={254}
              width={140}
              label="Verification"
              sublabel="provider-aware"
              accent
            />
            <Arrow d="M300,282 C220,282 130,282 80,202" />

            <text
              x={170}
              y={296}
              textAnchor="middle"
              className="fill-slate-500 text-[10px]"
            >
              verified response
            </text>
          </svg>
        </GlassCard>
      </motion.div>
    </section>
  );
}
